config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_one :child_of_father, class_name: 'User', foreign_key: :father_id
    has_one :child_of_mother, class_name: 'User', foreign_key: :mother_id
    has_one :step_child_of_father, class_name: 'User', foreign_key: :step_father_id
    has_one :step_child_of_mother, class_name: 'User', foreign_key: :step_mother_id
    belongs_to :father, class_name: 'User', optional: true, foreign_key: :father_id
    belongs_to :mother, class_name: 'User', optional: true, foreign_key: :mother_id
    belongs_to :step_father, class_name: 'User', optional: true, foreign_key: :step_father_id
    belongs_to :step_mother, class_name: 'User', optional: true, foreign_key: :step_mother_id

    enum gender: [ :male, :female ]

    scope :children, ->(user_id) { where('father_id= ? OR mother_id= ?', user_id,user_id) }
    scope :step_children, ->(user_id) { where('step_father_id= ? OR step_mother_id= ?', user_id,user_id) }

    validates :adharnumber, presence: true, numericality: { only_integer: true }, uniqueness: true
    validates :name, presence: true
    validate :check_if_step_parents_option_is_true

    def check_if_step_parents_option_is_true
        if self.has_step_parents == false && (self.step_father.present? || self.step_mother.present?)
            self.errors.add(:has_step_parents, "turn this option to true")
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(created_at: :desc).page(params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :adharnumber, :birthdate, :father, :mother, :children, :mother_id, :father_id, :gender, :step_father_id, :step_mother_id, :has_step_parents)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hindustaani</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :name %>
  <%= f.input :adharnumber %>
  <%= f.input :birthdate %>
  <%= f.input :gender, :as => :select, :collection => User.genders.keys, include_blank: false, include_hidden: false %>
  <%= f.input :father_id, collection: User.where(gender: "male").map {|user| [user.adharnumber, user.id]}%>
  <%= f.input :mother_id, collection: User.where(gender: "female").map {|user| [user.adharnumber, user.id]}%>
  <%= f.input :has_step_parents, :as => :select, :collection => [['No', false],['Yes', true]] %>
  <%= f.input :step_father_id, collection: User.where(gender: "male").map {|user| [user.adharnumber, user.id]}%>
  <%= f.input :step_mother_id, collection: User.where(gender: "female").map {|user| [user.adharnumber, user.id]}%>
  <%= f.button :submit, class: "btn-primary" %>
  <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Hindustani</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Adharnumber</th>
      <th>Birthdate</th>
      <th>Father</th>
      <th>Mother</th>
      <th>Children</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <% @users.each do |user| %>
     
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.adharnumber %></td>
        <td><%= user.birthdate %></td>
        <td><%= link_to user.father.name, user_path(user.father) if user.father  %></td>
        <td><%= link_to user.mother.name, user_path(user.mother) if user.mother  %></td>
        <td>
          <% if user.gender == "male" %>
            <%= link_to user.child_of_father.name, user_path(user.child_of_father) if user.child_of_father %>
          <% else %>
            <%= link_to user.child_of_mother.name, user_path(user.child_of_mother) if user.child_of_mother %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

    <% end %>
   
  </tbody>
</table>
<%= paginate @users %>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Adharnumber:</strong>
  <%= @user.adharnumber %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @user.birthdate %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @user.father.name if @user.father %>
</p>

<p>
  <strong>Mother name:</strong>
  <%= @user.mother.name if @user.mother %>
</p>

<p>
  <strong>Step father name:</strong>
  <%= @user.step_father.name if @user.step_father %>
</p>

<p>
  <strong>Step mother name:</strong>
  <%= @user.step_mother.name if @user.step_mother %>
</p>


<p>
  <strong>Children name:</strong>

  <% if @user.gender == "male" %>
    <%= @user.child_of_father.name if @user.child_of_father %>
  <% else %>
    <%= @user.child_of_mother.name if @user.child_of_mother %>
  <% end %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>


<p>
  <strong>Children:</strong>
   <%= User.children(@user).map { |user| link_to user.name, user_path(user)}.join(",").html_safe  %>
</p>


<p>
  <strong>Step Children:</strong>
   <%= User.step_children(@user).map { |user| link_to user.name, user_path(user)}.join(",").html_safe  %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>